param(
    [switch]$InstallComfyUI,
    [switch]$DownloadBaseModel,
    [string]$ComfyUIRoot,
    [string]$ModelRoot
)

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'Workflow.Common.ps1')

$projectRoot = Get-XianxiaProjectRoot
$toolchain = Get-Content -LiteralPath (Join-Path $projectRoot 'AI\toolchain.lock.json') -Raw | ConvertFrom-Json
$defaultInstallParent = Join-Path $env:LOCALAPPDATA 'XianxiaRogue\ImageLab'
$defaultComfyRoot = Join-Path $defaultInstallParent 'ComfyUI_windows_portable'

if ([string]::IsNullOrWhiteSpace($ComfyUIRoot)) {
    $ComfyUIRoot = $defaultComfyRoot
}

if ($InstallComfyUI -and -not (Test-Path -LiteralPath (Join-Path $ComfyUIRoot 'ComfyUI\main.py'))) {
    if ($ComfyUIRoot -ne $defaultComfyRoot) {
        throw 'Automatic installation uses the default portable path. Omit -ComfyUIRoot or install manually and pass its existing path.'
    }

    New-Item -ItemType Directory -Force -Path $defaultInstallParent | Out-Null
    $releaseTag = $toolchain.comfyui.release_tag
    $releaseUri = "https://api.github.com/repos/$($toolchain.comfyui.repository)/releases/tags/$releaseTag"
    $release = Invoke-RestMethod -Uri $releaseUri -Headers @{ 'User-Agent' = 'XianxiaRogue-Workstation-Bootstrap' }
    $asset = $release.assets | Where-Object {
        $_.name -eq $toolchain.comfyui.windows_nvidia_asset_name
    } | Select-Object -First 1

    if (-not $asset) {
        throw 'The latest official ComfyUI release did not expose a Windows NVIDIA portable archive.'
    }
    if ([long]$asset.size -ne [long]$toolchain.comfyui.windows_nvidia_asset_size_bytes) {
        throw 'The official ComfyUI asset size differs from the repository lock file. Review the release before updating the lock.'
    }

    $archive = Join-Path ([IO.Path]::GetTempPath()) ("xianxiarogue-comfyui-{0}.7z" -f $release.tag_name)
    Write-Output ("Downloading official ComfyUI portable {0}..." -f $release.tag_name)
    & (Join-Path $PSScriptRoot 'Download-LockedFile.ps1') `
        -Uri $asset.browser_download_url `
        -OutputPath $archive `
        -TotalBytes ([long]$toolchain.comfyui.windows_nvidia_asset_size_bytes) `
        -Sha256 $toolchain.comfyui.windows_nvidia_asset_sha256

    $tar = Get-Command tar -ErrorAction SilentlyContinue
    if (-not $tar) {
        throw 'Windows tar/libarchive is required to extract the official .7z portable package.'
    }

    & $tar.Source -xf $archive -C $defaultInstallParent
    if ($LASTEXITCODE -ne 0) {
        throw 'ComfyUI portable extraction failed.'
    }
    Remove-Item -LiteralPath $archive -Force
}

if ([string]::IsNullOrWhiteSpace($ModelRoot)) {
    $existingModelRoot = Join-Path $env:USERPROFILE 'ComfyUI\models'
    if (Test-Path -LiteralPath $existingModelRoot) {
        $ModelRoot = $existingModelRoot
    } else {
        $ModelRoot = Join-Path $ComfyUIRoot 'ComfyUI\models'
    }
}

$lock = Get-Content -LiteralPath (Join-Path $projectRoot 'AI\models.lock.json') -Raw | ConvertFrom-Json
$baseModel = $lock.models | Where-Object { $_.status -eq 'approved-baseline' } | Select-Object -First 1
$checkpointDirectory = Join-Path $ModelRoot 'checkpoints'
$checkpointPath = Join-Path $checkpointDirectory $baseModel.filename

if ($DownloadBaseModel) {
    New-Item -ItemType Directory -Force -Path $checkpointDirectory | Out-Null
    if (Test-Path -LiteralPath $checkpointPath) {
        $existingHash = Get-XianxiaSha256 -Path $checkpointPath
        if ($existingHash -ne $baseModel.sha256) {
            throw "A different file already exists at $checkpointPath. It was not overwritten."
        }
    } else {
        Write-Output ("Downloading {0} ({1} bytes)..." -f $baseModel.filename, $baseModel.size_bytes)
        Invoke-WebRequest -Uri $baseModel.download_url -OutFile $checkpointPath
    }
}

$envText = @(
    '# Generated by Tools/Bootstrap-Workstation.ps1. Do not commit.',
    ('COMFYUI_ROOT={0}' -f (ConvertTo-ForwardSlashPath $ComfyUIRoot)),
    ('COMFYUI_MODEL_ROOT={0}' -f (ConvertTo-ForwardSlashPath $ModelRoot)),
    ('COMFYUI_BASE_URL=http://127.0.0.1:{0}' -f $toolchain.comfyui.default_port)
) -join [Environment]::NewLine
[IO.File]::WriteAllText((Join-Path $projectRoot '.env.local'), $envText + [Environment]::NewLine, [Text.UTF8Encoding]::new($false))

if (Get-Command git -ErrorAction SilentlyContinue) {
    & git -c ("safe.directory={0}" -f $projectRoot) -C $projectRoot lfs install --local | Out-Null
}

Write-Output 'Local configuration written to .env.local.'
& (Join-Path $PSScriptRoot 'Verify-Workflow.ps1') -Deep
